[package]
name = "ortelius"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "*"
vello = { git = "https://github.com/linebender/vello.git" }
# vello = "*"
winit = "*"
pollster = "*"
rand = "0.9.2"
rand_distr = "0.5.1"
